"""Analyze ablation results and generate a LaTeX table.

The preferred input is ``results/ablation_summary.csv`` generated by
``scripts/run_ablation.py``. That file contains multi-seed mean/std results.
Legacy per-run log parsing is kept only as a fallback for old outputs.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

import pandas as pd

from src.experiment_names import ABLATION_NAMES


ABLATION_META = {
    "ab-1": {"fedprox": "No", "strategy": "size\\_only", "llm": "No", "rounds": 20},
    "ab-2": {"fedprox": "Yes", "strategy": "size\\_only", "llm": "No", "rounds": 20},
    "ab-3": {"fedprox": "Yes", "strategy": "perf\\_only", "llm": "No", "rounds": 20},
    "ab-4": {"fedprox": "Yes", "strategy": "hybrid", "llm": "No", "rounds": 20},
    "ab-5": {"fedprox": "Yes", "strategy": "Dynamic", "llm": "Yes", "rounds": 20},
    "ab-6": {"fedprox": "Yes", "strategy": "Dynamic+BC", "llm": "Yes", "rounds": 20},
}

ABLATION_ORDER = list(ABLATION_META.keys())


def _display_name(ab_id: str) -> str:
    return ABLATION_NAMES.get(ab_id, ab_id)


def _metric_mean(row: pd.Series, metric: str):
    corrected = f"{metric}_corrected"
    if row.get("id") == "ab-6" and f"{corrected}_mean" in row and pd.notna(row.get(f"{corrected}_mean")):
        return row.get(f"{corrected}_mean")
    if f"{metric}_mean" in row and pd.notna(row.get(f"{metric}_mean")):
        return row.get(f"{metric}_mean")
    return row.get(metric)


def _metric_std(row: pd.Series, metric: str):
    corrected = f"{metric}_corrected"
    if row.get("id") == "ab-6" and f"{corrected}_std" in row and pd.notna(row.get(f"{corrected}_std")):
        return row.get(f"{corrected}_std")
    if f"{metric}_std" in row and pd.notna(row.get(f"{metric}_std")):
        return row.get(f"{metric}_std")
    return None


def _format_metric(row: pd.Series, metric: str, pct: bool = False, dollar: bool = False) -> str:
    mean = _metric_mean(row, metric)
    if pd.isna(mean):
        return "-"

    std = _metric_std(row, metric)
    multiplier = 100 if pct else 1
    if pd.notna(std):
        if dollar:
            return f"{mean:,.0f} $\\pm$ {std:,.0f}"
        return f"{mean * multiplier:.2f} $\\pm$ {std * multiplier:.2f}" if pct else f"{mean:.4f} $\\pm$ {std:.4f}"

    if dollar:
        return f"{mean:,.0f}"
    return f"{mean * multiplier:.2f}" if pct else f"{mean:.4f}"


def _with_metadata(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df

    out = df.copy()
    out["id"] = out["id"].astype(str)
    out = out[out["id"].isin(ABLATION_META)].copy()
    order = {ab_id: idx for idx, ab_id in enumerate(ABLATION_ORDER)}
    out["_order"] = out["id"].map(order)
    out = out.sort_values("_order").drop(columns=["_order"])

    out["name"] = out["id"].map(_display_name)
    for col in ("fedprox", "strategy", "llm", "rounds"):
        out[col] = out["id"].map(lambda ab_id: ABLATION_META[ab_id][col])
    return out


def load_multi_seed_summary(results_dir: str = "results") -> pd.DataFrame:
    path = Path(results_dir) / "ablation_summary.csv"
    if not path.exists():
        return pd.DataFrame()
    return _with_metadata(pd.read_csv(path))


def extract_metrics_from_log(log_path: Path, use_bias_corrected: bool = False) -> dict:
    content = log_path.read_text(encoding="utf-8", errors="replace")

    if use_bias_corrected and "[Bias Correction] Test Results" in content:
        block = content.split("[Bias Correction] Test Results", 1)[1][:500]
    elif "Test Set Results (using best checkpoint):" in content:
        block = content.split("Test Set Results (using best checkpoint):", 1)[1][:500]
    else:
        block = content

    patterns = {
        "test_mape": r"MAPE:\s+([\d.]+)%",
        "test_rmse": r"RMSE:\s+\$([\d,]+\.?\d*)",
        "test_mae": r"MAE:\s+\$([\d,]+\.?\d*)",
        "test_mpe": r"MPE:\s+([-\d.]+)%",
        "test_r2": r"R2:\s+([-\d.]+)",
    }

    metrics = {}
    for key, pattern in patterns.items():
        match = re.search(pattern, block)
        if not match:
            continue
        value = float(match.group(1).replace(",", ""))
        if key in ("test_mape", "test_mpe"):
            value /= 100.0
        metrics[key] = value

    best_round_match = re.search(r"Best [Rr]ound[:\s]+(\d+)", content)
    if best_round_match:
        metrics["best_round"] = int(best_round_match.group(1))

    return metrics


def collect_ablation_results(results_dir: str = "results") -> pd.DataFrame:
    summary = load_multi_seed_summary(results_dir)
    if not summary.empty:
        return summary

    log_dir = Path(results_dir) / "ablation_logs"
    if not log_dir.exists():
        print("[WARN] ablation_logs directory not found.")
        return pd.DataFrame()

    rows = []
    for ab_id in ABLATION_ORDER:
        log_files = sorted(log_dir.glob(f"{ab_id}_*.log"))
        if not log_files:
            print(f"  [SKIP] {ab_id}: no log file found")
            continue

        metrics = extract_metrics_from_log(log_files[0], use_bias_corrected=(ab_id == "ab-6"))
        if not metrics:
            print(f"  [SKIP] {ab_id}: could not extract metrics from {log_files[0].name}")
            continue

        rows.append({"id": ab_id, **metrics})

    return _with_metadata(pd.DataFrame(rows))


def print_summary_table(df: pd.DataFrame) -> None:
    print("\n" + "=" * 90)
    print("ABLATION STUDY RESULTS")
    print("=" * 90)
    print(f"{'ID':<6} {'Name':<32} {'N':>4} {'MAPE%':>16} {'RMSE$':>22} {'R2':>16}")
    print("-" * 90)

    for _, row in df.iterrows():
        n = row.get("n_seeds", row.get("n_runs", 1))
        n_text = "-" if pd.isna(n) else str(int(n))
        print(
            f"{row['id']:<6} {_display_name(row['id']):<32} {n_text:>4} "
            f"{_format_metric(row, 'test_mape', pct=True):>16} "
            f"{_format_metric(row, 'test_rmse', dollar=True):>22} "
            f"{_format_metric(row, 'test_r2'):>16}"
        )

    print("=" * 90)

    mape_vals = {row["id"]: _metric_mean(row, "test_mape") for _, row in df.iterrows()}
    print("\nComponent contribution on MAPE (positive means lower MAPE):")
    comparisons = [
        ("FedProx", "ab-1", "ab-2"),
        ("Performance weighting", "ab-2", "ab-3"),
        ("Hybrid vs performance-only", "ab-3", "ab-4"),
        ("LLM dynamic selection", "ab-4", "ab-5"),
        ("Bias correction", "ab-5", "ab-6"),
        ("Total ab-1 to ab-5", "ab-1", "ab-5"),
    ]
    for label, left, right in comparisons:
        if left not in mape_vals or right not in mape_vals:
            continue
        if pd.isna(mape_vals[left]) or pd.isna(mape_vals[right]):
            continue
        delta = (mape_vals[left] - mape_vals[right]) * 100
        print(f"  {label}: {delta:+.2f} percentage points")


def generate_latex_table(df: pd.DataFrame) -> str:
    print("\n" + "=" * 70)
    print("LaTeX Table: Ablation Study Results")
    print("=" * 70)

    latex = r"""
\begin{table}[htbp]
\centering
\caption{Ablation Study: Component Contribution Analysis}
\label{tab:ablation}
\begin{tabular}{lcccccc}
\toprule
Configuration & FedProx & Strategy & LLM & MAPE (\%) $\downarrow$ & RMSE (\$) $\downarrow$ & $R^2$ $\uparrow$ \\
\midrule
"""

    for _, row in df.iterrows():
        latex += (
            f"{_display_name(row['id'])} & {row['fedprox']} & {row['strategy']} & {row['llm']} & "
            f"{_format_metric(row, 'test_mape', pct=True)} & "
            f"{_format_metric(row, 'test_rmse', dollar=True)} & "
            f"{_format_metric(row, 'test_r2')} \\\\\n"
        )

    latex += r"""
\bottomrule
\end{tabular}
\end{table}
"""

    print(latex)
    return latex


def main() -> None:
    print("=" * 70)
    print("ABLATION ANALYSIS")
    print("=" * 70)

    df = collect_ablation_results()
    if df.empty:
        print("\nNo results found. Please run ablation experiments first:")
        print("  python scripts/run_ablation.py")
        return

    print_summary_table(df)
    latex = generate_latex_table(df)

    latex_path = Path("results") / "ablation_table.tex"
    latex_path.parent.mkdir(parents=True, exist_ok=True)
    with open(latex_path, "w", encoding="utf-8") as f:
        f.write(latex)
    print(f"Saved LaTeX to {latex_path}")


if __name__ == "__main__":
    main()
