"""Audit the canonical project data and write a concise Markdown report."""

from pathlib import Path
from typing import Any

import pandas as pd


RAW_DATA = Path("Data/all_Data/Client_Data_Split_Cleaned.csv")
PROCESSED_DATA = Path("Data/processed/Client_Data_Split_Cleaned_EN.csv")
COMPANY_FILES = [
    Path("Data/processed/Company_A_train.csv"),
    Path("Data/processed/Company_B_train.csv"),
    Path("Data/processed/Company_C_train.csv"),
]
EXPECTED_RAW_COLUMNS = [
    "Dist区域",
    "BIDS投标数量",
    "WorkDays工期",
    "Length长度",
    "Lanes车道数",
    "ContDays合同日期",
    "ContAmnt合同金额",
    "CPPR承包商绩效评分",
    "CPI消费物价指数",
    "ConstSpndg建设投资支出",
    "PLR基准贷款利率",
    "PPI (2 year lag)生产物价指数",
    "ActualAmnt实际结算金额",
    "Client",
]
EXPECTED_CLIENT_COUNTS = {"Client 1": 233, "Client 2": 235, "Client 3": 220}


def _rel(path: Path, base: Path) -> str:
    return path.relative_to(base).as_posix()


def audit_current_dataset(base: Path | str = ".", expected_rows: int = 688) -> dict[str, Any]:
    """Audit the canonical raw dataset used by the current experiment pipeline."""
    base = Path(base)
    path = base / RAW_DATA
    df = pd.read_csv(path)
    missing_columns = [col for col in EXPECTED_RAW_COLUMNS if col not in df.columns]
    target = "ContAmnt合同金额"
    client_counts = df["Client"].value_counts().sort_index().to_dict() if "Client" in df.columns else {}

    issues = []
    if len(df) != expected_rows:
        issues.append(f"expected {expected_rows} rows, found {len(df)}")
    if missing_columns:
        issues.append(f"missing columns: {missing_columns}")
    if int(df.isna().sum().sum()) != 0:
        issues.append("contains missing values")
    if int(df.duplicated().sum()) != 0:
        issues.append("contains duplicated rows")
    if expected_rows == 688 and client_counts != EXPECTED_CLIENT_COUNTS:
        issues.append(f"unexpected client distribution: {client_counts}")

    return {
        "path": _rel(path, base),
        "rows": int(len(df)),
        "columns": list(df.columns),
        "missing_columns": missing_columns,
        "null_cells": int(df.isna().sum().sum()),
        "duplicate_rows": int(df.duplicated().sum()),
        "client_counts": client_counts,
        "target_min": float(df[target].min()) if target in df.columns else None,
        "target_mean": float(df[target].mean()) if target in df.columns else None,
        "target_max": float(df[target].max()) if target in df.columns else None,
        "status": "PASS" if not issues else "FAIL",
        "issues": issues,
    }


def audit_processed_dataset(base: Path | str = ".") -> dict[str, Any]:
    """Audit the English-column processed dataset regenerated by the pipeline."""
    base = Path(base)
    path = base / PROCESSED_DATA
    df = pd.read_csv(path)
    return {
        "path": _rel(path, base),
        "rows": int(len(df)),
        "columns": list(df.columns),
        "null_cells": int(df.isna().sum().sum()),
        "duplicate_rows": int(df.duplicated().sum()),
        "client_counts": df["Client"].value_counts().sort_index().to_dict(),
        "target_min": float(df["ContAmnt"].min()),
        "target_mean": float(df["ContAmnt"].mean()),
        "target_max": float(df["ContAmnt"].max()),
    }


def classify_company_file(name: str, df: pd.DataFrame) -> dict[str, Any]:
    """Classify old Company_* files so they are not mistaken for current clients."""
    target = df["ContAmnt"] if "ContAmnt" in df.columns else pd.Series(dtype=float)
    return {
        "name": name,
        "rows": int(len(df)),
        "target_min": float(target.min()) if not target.empty else None,
        "target_max": float(target.max()) if not target.empty else None,
        "role": "legacy_amount_stratum",
        "note": "Historical amount-stratified training file; not a current client split.",
    }


def audit_legacy_company_files(base: Path | str = ".") -> list[dict[str, Any]]:
    base = Path(base)
    records = []
    for rel_path in COMPANY_FILES:
        path = base / rel_path
        if path.exists():
            records.append(classify_company_file(path.name, pd.read_csv(path)))
    return records


def write_markdown_report(base: Path | str = ".", output: Path | str = "docs/data_audit_report.md") -> Path:
    base = Path(base)
    output_path = base / output
    current = audit_current_dataset(base)
    processed = audit_processed_dataset(base)
    legacy = audit_legacy_company_files(base)

    lines = [
        "# Data Audit Report",
        "",
        "## Canonical Dataset",
        "",
        f"- Path: `{current['path']}`",
        f"- Status: **{current['status']}**",
        f"- Rows: {current['rows']}",
        f"- Null cells: {current['null_cells']}",
        f"- Duplicate rows: {current['duplicate_rows']}",
        f"- Client distribution: {current['client_counts']}",
        f"- Target range: {current['target_min']:,.2f} to {current['target_max']:,.2f}",
        "",
        "## Processed Dataset",
        "",
        f"- Path: `{processed['path']}`",
        f"- Rows: {processed['rows']}",
        f"- Columns: {', '.join(processed['columns'])}",
        f"- Null cells: {processed['null_cells']}",
        f"- Duplicate rows: {processed['duplicate_rows']}",
        "",
        "## Legacy Company Files",
        "",
    ]
    for item in legacy:
        lines.append(
            f"- `{item['name']}`: {item['rows']} rows, ContAmnt "
            f"{item['target_min']:,.2f}-{item['target_max']:,.2f}; {item['note']}"
        )

    lines.extend([
        "",
        "## Interpretation",
        "",
        "The current experiments should use the 688-row client-labelled dataset. "
        "The old Company_A/B/C files are retained only as historical amount strata.",
        "",
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def main() -> None:
    path = write_markdown_report()
    print(f"Data audit written to {path}")


if __name__ == "__main__":
    main()
